spring:
  datasource:
    url: jdbc:mysql://localhost:8888/dev?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false&verifyServerCertificate=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
